model:
    arch: unet_octconv
    alpha: 0.25
data:
    dataset: cityscapes
    train_split: train
    val_split: val
    img_rows: 1024
    img_cols: 2048
    path: ../data/cityscapes
training:
    train_iters: 100000
    batch_size: 2
    val_interval: 1000
    print_interval: 50
    optimizer:
        lr: 1.0e-4
        name: adam
    lr_schedule:
        name: poly_lr
        max_iter: 100000
    momentum: 0.99
    weight_decay: 0.0005
    resume: unet_octconv_best_model.pkl
    visdom: False
    n_workers: 2
    loss:
        name: cross_entropy
    augmentations:
        hue: 0.1
        brightness: 0.3
        saturation: 0.3
        translate: [16, 16]
        hflip: 0.5
