model:
    arch: unet_baseline
data:
    dataset: cityscapes
    train_split: train
    val_split: val
    img_rows: 512
    img_cols: 1024
    path: ../data/cityscapes
training:
    train_iters: 178500  # ~240 epochs at batchsize=4
    batch_size: 4
    val_interval: 500
    print_interval: 25
    optimizer:
        lr: 1.0e-3
        name: adam
    lr_schedule:
        name: poly_lr
        max_iter: 178500
    momentum: 0.99
    weight_decay: 0.0005
    resume: unet_baseline_best_model.pkl
    visdom: False
    n_workers: 2
    loss:
        name: cross_entropy
    augmentations:
        hue: 0.1
        brightness: 0.3
        saturation: 0.3
        rcrop: [496, 1008]
        hflip: 0.5
