model:
    arch: unet_octconv
    alpha: 0.25
data:
    dataset: lip_single_human_parsing
    train_split: train
    val_split: val
    img_rows: 288
    img_cols: 288
    path: ../data/lip_single_human_parsing
training:
    train_iters: 100000
    batch_size: 24
    val_interval: 1000
    print_interval: 50
    optimizer:
        lr: 5.0e-4
        name: adam
    lr_schedule:
        name: cosine_annealing
        T_max: 100000
        warmup_iters: 1000
        warmup_mode: linear
        warmup_factor: 0.2
    resume: unet_baseline_best_model.pkl
    visdom: False
    n_workers: 2
    loss:
        name: cross_entropy
    augmentations:
        rcrop: [256, 256]
        hue: 0.1
        brightness: 0.3
        saturation: 0.3
